"""add table person

Revision ID: 1b54c80e87b6
Revises: 500ded61d360
Create Date: 2022-08-18 16:05:57.743502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b54c80e87b6'
down_revision = '500ded61d360'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Persons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Persons',
    sa.Column('PersonID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FirstName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
