"""add column test1

Revision ID: 07e9950d3749
Revises: e6f51b8178f1
Create Date: 2022-08-20 01:07:12.458155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e9950d3749'
down_revision = 'e6f51b8178f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test1', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test1')
    # ### end Alembic commands ###
