"""init

Revision ID: 26197cddbdf3
Revises: 
Create Date: 2022-08-20 00:36:52.696985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26197cddbdf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
