"""add column test2

Revision ID: eff1b556ff52
Revises: e6f51b8178f1
Create Date: 2022-08-20 01:11:13.852339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff1b556ff52'
down_revision = 'e6f51b8178f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test2', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test2')
    # ### end Alembic commands ###
